# -*- mode: ruby -*-
# vi: set ft=ruby :

# Requires the vagrant-vbguest plugin
#   vagrant plugin install vagrant-vbguest

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  # sets up the parent directory as the synced folder, so you can place the Vagrantfile in a sub-dir in your workspace
  # e.g.
  #   ~/workspace/
  #   ~/workspace/vm-cpp
  #   ~/workspace/vm-cpp/Vagrantfile
  config.vm.synced_folder "..", "/vagrant",
    owner: "vagrant", group: "vagrant", type: "virtualbox"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 1
    vb.name = "vm-cpp"
  end

  config.vm.provision "shell", inline: <<-SHELL
    yum update -y
    yum install -y epel-release
    yum install -y gcc-c++ cmake3 make git vim wget 
    wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    chmod +x miniconda.sh
    ./miniconda.sh -b -p /home/vagrant/miniconda
    echo 'export PATH="/home/vagrant/miniconda/bin:$PATH"' >> /home/vagrant/.bashrc
    source /home/vagrant/.bashrc
    chown -R vagrant:vagrant /home/vagrant/miniconda
  SHELL
end
